### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by emumanu** [r-murphy/openui5-types#1]
Hello,

Following the instructions of the README.MD gives error in this step:

npm install openui5-types --save

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "openui5-types" under a package
npm ERR! also called "openui5-types". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

I have to change the name in package.json to make it work.

also, the suggested tsconfig.json in the README.MD, doesn't even have properly matched curly braces. Could you please post an updated tsconfig.json that I can run in vs code without further changes?

**Comment by r-murphy** [comment]
@emumanu was your project also named `openui5-types`? If so then this error is expected and there's nothing I can do from this module. 

I fixed the mismatched braces in the readme. Thanks for pointing that out.
I also added a link to an example project and also a babel plugin for transforming classes and modules.

**Comment by emumanu** [comment]
thank you @r-murphy
